echo "starting game"
echo "But when is the last time you actually thought about PDFs? The tempo of digital culture is set by fast-paced, head-snapping novelty. So it’s probably been a while — or more likely, never — since you stopped to think where the ubiquitous PDF came from. The Portable Document Format that essentially strives to replicate paper in digital form has been around since the early pre-Web 1990s. Thoroughly lacking in glamor or sizzle, the PDF has not only persisted for decades, but prevailed. Even stalwarts like Microsoft Word or PowerPoint get challenged by rival offerings from Google or Apple. But no PDF-killer has emerged. In fact, PDF inventor Adobe reports that in its 2020 fiscal year alone, about 303 billion PDFs were opened using its Document Cloud service — a 17% annual increase during a year in which the tech conversation was dominated by things like videoconferencing, autonomous vehicles, and facial recognition technology.
Clearly, we take the PDF’s indestructibility for granted. The PDF is a digital equivalent to a paper clip or a ballpoint pen — an everyday tool so familiar it seems to have come out of nowhere, yet it’s hard to imagine its absence. But none of these objects came out of nowhere, of course: They were all designed, engineered, created, refined. In the case of the PDF, what was crucial to its long-term success was the decision by the business that invented it to essentially give its creation away.
The individual most closely identified with the invention of the PDF is John Warnock, who co-founded Adobe in 1982 with Charles Geschke. The two left Xerox PARC to build a business — originating in Warnock’s garage, of course — around a technology called PostScript, basically a language for making computer documents easily printable.
While the company also went on to develop several iconic products — Illustrator and Photoshop are famous examples — Warnock had a preoccupation that was somewhat adjacent to PostScript’s bridging of the digital and the analog. In the early 1990s, he launched Camelot, a code-named project that sought to create a file format that worked across operating systems, and would look the same if printed out on any printer. That was a real challenge at a time when a document created in MS-DOS or Unix might look like gobbledygook on a Mac, and vice versa. (You can read Warnock’s original six-page Camelot memo — as a PDF, natch — here.)
An official Adobe history describes the PDF’s goal as being able to “exchange information between machines, between systems, between users in a way that ensured that the file would look the same everywhere it went.” This meant creating “a digital interchange format that preserved author intent,” says David Parmenter, director of engineering for Adobe Document Cloud, “which is, at a really high level, what a PDF tries to do.”
Beneath the highly technical language is something pretty basic: The mission of the PDF is simply to be the digital version of old-fashioned paper.
Paper, in combination with fairly dull-seeming technologies like photocopying and physical delivery, accomplished that critical mission: “If I send [a document] to you, I want you and I to agree that it looks the same,” Parmenter says. The PDF achieved this in a computationally efficient way, making a document that not only transcended platforms, but was small enough to share electronically even three decades ago.
Warnock’s idea in part was actually to replace paper, putting the PDF at the center of the long-sought yet ever-chimerical dream of the paperless office. Others were pursuing the same goals, and the 1990s saw a flurry of competitors such as DjVu, WordPerfect’s Envoy, Common Ground Digital Paper, and others aspiring to become the one true standard — the paper of the emerging digital world.
This wasn’t simply an intellectual endeavor; winning this contest could be lucrative. Adobe announced the coming of the PDF at a buzzy tech conference in 1992, and the following year released software for creating and reading the format. According to one history, Adobe’s debut PDF-making program cost users about $700, and its Acrobat reader tool cost $50. As a business gambit, this was not an immediate success. “The world didn’t get it,” Warnock later said, adding that Adobe’s board wanted to kill Acrobat outright. Aside from the cost factor, PDFs were more cumbersome than plain text, and slower to download over typical modems at the time.
Still, the company made important decisions setting a tone for the PDF’s future. Upon its 1993 release, the specs of the PDF format were made freely available. While Adobe’s specific version remained proprietary, others could tinker with it at will — “allowing it to become a de facto standard,” as a 2018 Vice overview of the format put it. Soon, the company dropped the fee for its reader software, focusing entirely on the creation product as a revenue stream — but gambling that the more people who could read the format, the more attractive it would be to the creator side.
Meanwhile, the brisk mainstreaming of the Web and steadily improving download speeds worked in the PDF’s favor. And in the mid-1990s it was embraced by a pivotal user: the Internal Revenue Service. For the IRS, mailing tax forms to more than 100 million households was a complicated and expensive enterprise. Making forms available for download in a reliable format like the PDF was a breakthrough. The government agency’s prominent example served as a case study that showed the PDF’s value to business, academia, law firms, medicine, and others. A big part of that value was the form’s stability and universality — its basic resemblance, in short, to paper.
Of course, Adobe was simultaneously working to make the PDF better than paper. Over the years it has continuously added digital features, from supporting basic hyperlinks to improved answer fields to interactive elements and plug-ins to a proprietary scanning technology to custom digital signature options.
In 2008, the company took what was a decisive step in cementing the PDF’s role: It allowed the format’s specs to be published and ultimately controlled by the independent nongovernmental organization International Organization for Standardization, granting royalty-free rights to use of the relevant patents to make or sell uses of the PDF spec. While the company holds one seat on the relevant ISO committee and advises the ISO team with technical input, it has no more power than any other participant in shaping the format’s standards.
This is why there are now scads of PDF-creation tools and PDF readers beyond Adobe’s own products, and it’s why the format seems ubiquitous. If you want to save a Microsoft Word document as a PDF, that’s a simple choice built into the software; if someone sends you a PDF, you can just open it in whatever reader you’ve specified, or that your laptop or phone defaults to. The upshot is that while the humble PDF is not the only electronic document format on the web, it is wildly dominant.
And all of this worked out quite nicely for Adobe as a business. “Once we made it available to everybody, there was a big halo effect,” says Adobe’s Parmenter. “People naturally associate the PDF with Adobe.” Indeed, many people assume Adobe still somehow owns the format; while the company holds one seat on the relevant ISO committee that gives it no more power than any other participant in shaping the format’s standards. The PDF keeps spreading not because Adobe or any company forces others to use it, but because of “millions of people all over the world,” Parmenter says, “just doing their thing.”
There’s no question that the close association with the PDF has been vital to the long-running success of Acrobat, Adobe’s document software. Adobe successfully transitioned to a cloud/subscription model for its various business units a few years ago, and the ability to create and edit PDFs with all the latest bells and whistles with Acrobat is at the center of its Document Cloud offering, which had revenue of $1.5 billion in fiscal 2020, according to Adobe’s latest earnings report. The pandemic-sparked push toward digitizing workflow has only boosted the PDF’s role; a Forrester Research study the company commissioned found that company spending on digital document processes and tools could increase by more than 50% this year. Adobe’s revenue and profits were up across the board in 2020, and its shares rose from about $333 to more than $500.
Adobe’s most recent and ongoing efforts around the PDF have centered on adapting the format to the smartphone era. Late last year, the company debuted what it calls a “Liquid Mode” option that rejiggers PDFs for easier phone-screen-sized reading. On the creator and developer side, it has recently made the documents easier to embed in websites and is working on the ability to incorporate 3-dimensional renderings into PDFs.
But the real key to the dominance of the PDF has less to do with its future than with its roots. From the start, it was meant to be lightweight and forward compatible, meaning the format would continue to be readable. And according to Adobe, even the very first generation of PDFs remain legible to its latest reader tools. This is a strength that again echoes analog inspiration: If you pick up a 100-year-old book, you don’t need to download any updates to read it."

bash
python3 main.py
